services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - ./:/var/www/html
    depends_on:
      - database
    networks:
      - symfony

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - symfony

  database:
    image: mysql:8.3
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-drugcard}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-12345678}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - "3307:3306"
    volumes:
      - database_data:/var/lib/mysql:rw
    networks:
      - symfony

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - symfony

volumes:
  database_data:

networks:
  symfony:
